### ISSUE TITLE
Output to file/pipe

### ISSUE THREAD

**Issue by orukusaki** [orukusaki/magento-rest-test#5]
Currently the json response is mixed up with the other script output.  It might be nice to allow it to be fed into something else via one/more of:
- An option to output the response to a filename
- Write all debug info to stderr and only write the response json to stdout, to allow piping
- Use bash magic to detect a pipe, and then only output the response

There are doubtless other ways to achieve this too.
Would it actually be useful though?

**Comment by ShaneArmstrong** [comment]
### The idea

I wouldn't be against the idea of an optional argument for only writing the response content to stdout - it would definitely be useful to be able to pipe this properly.

For instance, pulling down data, piping it to modify it and then POST-ing it back is one potential usecase for creating mock test data, which is a direction we have been going on.

### Proposal

However, perhaps we should have the default to be just the response output of your request and supply a _[-v --verbose]_ option for people who want to see the full output?

**Comment by orukusaki** [comment]
I've decided on pushing all debug info to stderr, and only the response to stdout. That way, if you pipe the results to a file or another program, you'll only get the response body and not all the other fluff
